"""remove_slug_from_tags

Revision ID: 71cbe692399b
Revises: 133e3508aeac
Create Date: 2026-05-22 08:20:14.773047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71cbe692399b'
down_revision: Union[str, Sequence[str], None] = '133e3508aeac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_column('tags', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    # ### end Alembic commands ###
